### ISSUE TITLE
where to call enif_free(Pid)

### ISSUE THREAD

**Issue by CMShuyuhui** [davisp/nif-examples#5]
in source file 'nif-examples/apps/termsend_threaded/c_src/termsend_threaded.c' line 218:
you called 'ErlNifPid* pid = (ErlNifPid*) enif_alloc(sizeof(ErlNifPid));

but I couldn't see where you have called enif_free for this pid memory, is there have memory leak???

**Comment by davisp** [comment]
The memory for pid is freed by the thread after the message has been sent:

https://github.com/davisp/nif-examples/blob/c474fa2b05b743e0b7905df91968c9928b936b39/apps/termsend_threaded/c_src/termsend_threaded.c#L148
